apiVersion: v1
kind: Secret
metadata:
  name: user-postgres-secret
  namespace: eventticketing
type: Opaque
stringData:
  # Base64-encoded in production — using stringData here for readability
  POSTGRES_USER:     postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB:       etdb-users
  DATABASE_URL:      jdbc:postgresql://user-postgres:5432/etdb-users