spring:
  application:
    name: booking-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://booking-postgres:5432/etdb-bookings}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:rootpass@localhost:27017/eventticketingmongo?authSource=admin}
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
      password: ${SPRING_DATA_REDIS_PASSWORD:redispass}
    neo4j:
      uri: ${SPRING_NEO4J_URI:bolt://localhost:7687}
      authentication:
        username: ${SPRING_NEO4J_AUTHENTICATION_USERNAME:neo4j}
        password: ${SPRING_NEO4J_AUTHENTICATION_PASSWORD:neo4jpass}
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:rootpass@localhost:27017/eventticketingmongo?authSource=admin}
  web:
    error:
      include-message: always
      include-binding-errors: always
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto
        default-requeue-rejected: false
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:XTAA/1w8x3EU1gymE8NZpczBPdPcPeT3UpsSA2I+Utw=}
  expiration: ${JWT_EXPIRATION_MS:86400000}

feign:
  event-service:
    url: ${FEIGN_EVENT_SERVICE_URL:http://event-service:8080}
  user-service:
    url: ${FEIGN_USER_SERVICE_URL:http://user-service:8080}
  ticket-service:
    url: ${FEIGN_TICKET_SERVICE_URL:http://ticket-service:8080}
  sales-service:
    url: ${FEIGN_SALES_SERVICE_URL:http://sales-service:8080}
  booking-service:
    url: ${FEIGN_BOOKING_SERVICE_URL:http://booking-service:8080}

logging:
  level:
    com.team7.eventticketing.booking: DEBUG
