apiVersion: v1
kind: ConfigMap
metadata:
  name: sales-service-configmap
  namespace: eventticketing
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://sales-postgres:5432/etdb-sales
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_MONGODB_URI: mongodb://root:rootpass@mongo:27017/eventticketingmongo?authSource=admin

  FEIGN_BOOKING_SERVICE_URL: http://booking-service:8080
  FEIGN_USER_SERVICE_URL: http://user-service:8080
  FEIGN_EVENT_SERVICE_URL: http://event-service:8080