apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: eventticketing
  labels:
    app: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: booking-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: booking-service-config

          # Liveness Probe: Tells K8s if the app has crashed and needs a restart
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40  # Gives Spring Boot time to start up
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3

          # Readiness Probe: Tells K8s if the app is ready to receive traffic
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3