spring:
  application:
    name: sales-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/eventticketingdb}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:rootpass@localhost:27017/eventticketingmongo?authSource=admin}
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
      password: ${SPRING_DATA_REDIS_PASSWORD:redispass}

  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:rootpass@localhost:27017/eventticketingmongo?authSource=admin}
  web:
    error:
      include-message: always
      include-binding-errors: always

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:XTAA/1w8x3EU1gymE8NZpczBPdPcPeT3UpsSA2I+Utw=}
  expiration: ${JWT_EXPIRATION_MS:86400000}

logging:
  level:
    com.team7.eventticketing.sales: DEBUG