apiVersion: v1
kind: Service
metadata:
  name: sales-postgres-headless
  namespace: eventticketing
  labels:
    app: sales-postgres
spec:
  clusterIP: None
  selector:
    app: sales-postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: sales-postgres
  namespace: eventticketing
  labels:
    app: sales-postgres
spec:
  selector:
    app: sales-postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  type: ClusterIP