apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: booking-postgres
  namespace: eventticketing
spec:
  serviceName: booking-postgres
  replicas: 1
  selector:
    matchLabels:
      app: booking-postgres
  template:
    metadata:
      labels:
        app: booking-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: booking-postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: booking-postgres-secret
                  key: password
            - name: POSTGRES_DB
              value: etdb-bookings
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "etdb-bookings"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "etdb-bookings"]
            initialDelaySeconds: 30
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
